# Generated by Django 3.2.2 on 2021-06-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='subtitulo',
            field=models.SlugField(max_length=250, unique_for_date='data_publicacao'),
        ),
    ]
