# Generated by Django 3.2.4 on 2021-06-10 19:54

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('blogc', '0003_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='subtitulo',
            field=models.SlugField(help_text='<b style="color:black;">O subtitulo deve ser igual ao titulo, mas transcrito em minusculas e com espacos substituidos por (-)(hifens).<br>Ex: nome-para-a-publicacao.</b>', max_length=250, unique_for_date='data_publicacao'),
        ),
    ]
