# Generated by Django 3.2.4 on 2021-06-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogc', '0005_alter_publicacao_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='estado',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado')], default='rascunho', max_length=10),
        ),
    ]
